version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=''

      - DB_NAME=''
      - DB_USER=''
      - DB_PASSWORD=''
      - DB_HOST=''
      - DB_PORT=''

      - SECRET_KEY=''
    depends_on:
      - db
    volumes:
      - static_volume:/app/staticfiles 

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=default_user
      - POSTGRES_PASSWORD=saasdb
      - POSTGRES_DB=saasdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  static_volume: