version: '3.8'

services:
  web:
    build: ./saasproject
    ports:
      - "8000:8000"
    environment:
      - DEBUG=${DEBUG}

      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}

      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db
    env_file:
     - .env


  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
     - .env


volumes:
  postgres_data: